export enum DeliveryLifecycle {
  RECEIVED = 'RECEIVED',
  VALIDATED = 'VALIDATED',
  RENDERED = 'RENDERED',
  PROVIDER_RESOLVED = 'PROVIDER_RESOLVED',
  PROVIDER_INVOKED = 'PROVIDER_INVOKED',
  COMPLETED = 'COMPLETED',
}
