export const EXPENSE_CONSTANTS = {
  DEFAULT_CURRENCY: 'USD',
  MAX_RISK_SCORE_THRESHOLD: 80,
  DUPLICATE_RECEIPT_WEIGHT: 40,
  SPLIT_EXPENSE_WEIGHT: 25,
  REPEATED_VIOLATION_WEIGHT: 30,
  LARGE_AMOUNT_WEIGHT: 20,
  INTERNATIONAL_TRAVEL_WEIGHT: 10,
};
