export enum ExpenseStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  POLICY_VALIDATION = 'POLICY_VALIDATION',
  APPROVAL = 'APPROVAL',
  FINANCE_APPROVAL = 'FINANCE_APPROVAL',
  PAYROLL_REIMBURSEMENT = 'PAYROLL_REIMBURSEMENT',
  CLOSED = 'CLOSED',
}

export enum TravelStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  ADVANCE_ISSUED = 'ADVANCE_ISSUED',
  TRAVEL_STARTED = 'TRAVEL_STARTED',
  TRAVEL_COMPLETED = 'TRAVEL_COMPLETED',
  EXPENSE_SUBMITTED = 'EXPENSE_SUBMITTED',
  SETTLEMENT = 'SETTLEMENT',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum BudgetAction {
  REJECT = 'REJECT',
  ESCALATE = 'ESCALATE',
  WARN = 'WARN',
  IGNORE = 'IGNORE',
}

export enum BudgetReservationStatus {
  PENDING = 'PENDING',
  CONVERTED = 'CONVERTED',
  RELEASED = 'RELEASED',
}

export enum ReceiptOcrStatus {
  PENDING = 'PENDING',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
}

export enum CorporateCardImportStatus {
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
