export const ErrorCodes = {
  // Platform & Generic Errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  ACCESS_DENIED: 'ACCESS_DENIED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',

  // Employee Domain
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  EMPLOYEE_ALREADY_CONFIRMED: 'EMPLOYEE_ALREADY_CONFIRMED',
  EMPLOYEE_ALREADY_EXITED: 'EMPLOYEE_ALREADY_EXITED',
  EMPLOYEE_INACTIVE: 'EMPLOYEE_INACTIVE',
  INVALID_EMPLOYEE_STATE: 'INVALID_EMPLOYEE_STATE',
  
  // Persistence & Prisma Mapping
  DATABASE_CONFLICT: 'DATABASE_CONFLICT',
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND'
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
